### ISSUE TITLE
Get by hash endpoints only working with SHA-1

### ISSUE THREAD

**Issue by Zechiax** [masecla22/Modrinth4J#3]
This works:

`var version = api.versions().files().getVersionByHash(FileHash.SHA1, hash).join()`

but using `FileHash.SHA256` doesn't and I don't think Modrinth currently stores SHA-256 file hashes, only SHA-1 and SHA-512 [looking at the documentation](https://docs.modrinth.com/api-spec/#tag/version-files/operation/versionFromHash)

**Comment by masecla22** [comment]
You are right, I must have done it out of mental reflex. 

#5 should fix this once merged.
