### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PinkGoosik** [masecla22/Modrinth4J#7]
There should be an option to get all of the project's versions without getting the project, like versions().getProjectVersions() but without resticting to only featured of unfeatured versions

**Comment by masecla22** [comment]
This was introduced in Modrinth4J 2.2.0

getProjectVersions() will no longer search for unfeatured versions by default. It's now searching for both by default and will only restrict when the featured parameter is supplied to the builder.

Check out https://github.com/masecla22/Modrinth4J/blob/master/src/test/java/masecla/modrinth4j/client/VersionEndpointsTests.java#L100-L126
